const MIN_PASSWORD_LENGTH = 10;
const MAX_CARD_TITLE_LENGTH = 200;
const MAX_CARD_TEXT_LENGTH = 5000;
const MAX_TOPIC_NAME_LENGTH = 200;
const MAX_TOPIC_DESCRIPTION_LENGTH = 1000;

export {
  MIN_PASSWORD_LENGTH,
  MAX_CARD_TITLE_LENGTH,
  MAX_CARD_TEXT_LENGTH,
  MAX_TOPIC_NAME_LENGTH,
  MAX_TOPIC_DESCRIPTION_LENGTH
};
